---
- name: Fail if required variables are not defined
  assert:
    that: ("{{ item }} is defined") and ("{{ item }} | length > 0")
  with_items:
    - controller_fqdn
    - api_key

- name: COPY files/stub_status.conf /etc/nginx/conf.d/ https://www.nginx.com/blog/monitoring-nginx/
  copy:
    src: "files/stub_status.conf"
    dest: "/etc/nginx/conf.d/stub_status.conf"
    force: yes

- name: COPY files/nginx-plus-api.conf /etc/nginx/conf.d/ necessary for process monitoring.
  copy:
    src: "files/nginx-plus-api.conf"
    dest: "/etc/nginx/conf.d/nginx-plus-api.conf"
    force: yes

- name: download the installer script from controller
  get_url:
    url: "https://{{controller_fqdn}}:8443/1.4/install/controller/"
    dest: ~/install.sh
    validate_certs: no
    force: yes
  register: controller_return

- name: try to backup agent.conf
  copy:
    src: /etc/controller-agent/agent.conf
    dest: /etc/controller-agent/agent.bak
    force: yes
    remote_src: yes

- name: run the Controller Agent installer
  shell: |
    sh ./install.sh \
    API_KEY='{{api_key}}' \
    {{ (instance_name is defined) | ternary('CONTROLLER_HOSTNAME=' + instance_name,'') }} \
    {{ (location is defined) | ternary('-l ' + location,'') }} \
    {{ (instance_name is defined) | ternary('-i ' + instance_name,'') }}
  args:
    chdir: ~
  register: agent_install

- name: output agent install results
  debug:
    var: agent_install.stdout_lines

- name: stop controller registration to preserve agent.conf
  service:
    name: controller-agent
    state: stopped

- name: try to restore agent.conf
  copy:
    src: /etc/controller-agent/agent.bak
    dest: /etc/controller-agent/agent.json
    force: yes
    remote_src: yes

- name: start controller agent
  service:
    name: controller-agent
    state: started

- name: restart nginx
  service:
    name: nginx
    state: restarted